### ISSUE TITLE
Content: add "type" to all questions

### ISSUE THREAD

**Issue by dankrasno** [sandboxnu/edulaw#30]

**Comment by clue4** [comment]
Definitely having some trouble deciding which qs are which:
14 and 17 say "end of section" and point to nothing else - I've marked them as "RESULT" for now.
19, 20, 22, 23, 26, 32, 34, 36 I've marked as "RADIO", and their only option is a "next" button (so I think this is the correct choice?)
28, 38 - seem to be both text and radio as they ask for more text but also want a next button... I've marked them as text for now. 

and finally, in the Bullying lucid chart, there seem to be some blue boxes that are not routed to / do not have questions corresponding to them in the json.
