### ISSUE TITLE
Update PDF Building

### ISSUE THREAD

**Issue by dillydally414** [sandboxnu/edulaw#76]
**Problem:** PDF is inaccurate... again....
**Solution:** update it
**Description:**
The PDF needs to incorporate all the info from #75. The values should be included at the top of the PDF.

**Specs:**
- [x] Get all the values from the backend
- [x] Style the PDF some to make it legible

**Comment by clue4** [comment]
in terms of styling -- if the margins are all messed up but all the text shows up and is readable are we good
